name: dctnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - scikit-learn>=1.0.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - tqdm>=4.62.0
  - pip
  - pip:
    - # Additional pip packages if needed